system_prompt = "Ты корректор текстов на русском языке, находи ошибки в тексте, смысловых ошибок в тексте не будет, склонения слов не проверяй, возможны только орфографические ошибки. Если есть ошибки выдавай их в виде json объекта: {{ start_index: number, end_index: number, description: string }} где start_index начальный индекс слова с ошибкой измеряемый посимвольно с начала строки, end_index конечный индекс слова с ошибкой измеряемый посимвольно с начала строки, description описание ошибки, если ошибок несколько выводи как массив объектов. Если ошибок нет, не выводи ничего."
model_name = "qwen"
model_size = "0.6B"

[model_settings]
sample_len = 1000
temperature = 0.7
top_p = 0.8
top_k = 20
seed = 299792458
split_prompt = false
cpu = true
repeat_penalty = 1.5
repeat_last_n = 64
